### ISSUE TITLE
NullReferenceException when using SaveChangesAsync

### ISSUE THREAD

**Issue by johnhenley** [GibraltarSoftware/Gibraltar.Agent.EntityFramework#20]
Previously using Gibraltar.Agent.EntityFramework without issues.
After switching code to use SaveChangesAsync() rather than SaveChanges(), 
Diagnostic Tools flooded with NullReferenceException 

Yes, I have this in the code:
Gibraltar.Agent.EntityFramework.LoupeCommandInterceptor.Register();

I have even added this to web.config:
`
 <gibraltar>
.
.
.
      <entityFramework enabled="false" />
</gibraltar>`
but no effect.

![image](https://user-images.githubusercontent.com/9553126/41425455-c64787d8-6fce-11e8-8ded-2931b737fe53.png)

**Comment by kendallmiller** [comment]
That's not good; Do you have more call stack information to show where it is getting thrown exactly?  We do use SaveChangesAsync ourselves in Loupe so I'm wondering if there's more to it than we think.

**Comment by johnhenley** [comment]
Hi Kendall,

Thanks for the quick response.

I was able to get this tracked down to this code:

[cid:image001.png@01D403E7.85464290]

[cid:image004.jpg@01D403E7.856B56C0]

[cid:image005.jpg@01D403E7.856B56C0]

**Comment by kendallmiller** [comment]
Maybe it's just me but the images aren't coming through?

**Comment by johnhenley** [comment]
![image](https://user-images.githubusercontent.com/9553126/41431276-61673536-6fe0-11e8-9970-43e93c6ceacc.png)
![image](https://user-images.githubusercontent.com/9553126/41431279-6450a7f0-6fe0-11e8-91a3-14607b2d280d.png)
![image](https://user-images.githubusercontent.com/9553126/41431284-667a75b0-6fe0-11e8-8efc-450d0376d7c9.png)

**Comment by johnhenley** [comment]
Sorry about that; emailing the images doesn’t work with Github, so I have posted the images on the site

**Comment by kendallmiller** [comment]
That comment is totally sweet - nothing like the contradiction of saying "can't return null" and getting a null.

**Comment by kendallmiller** [comment]
This is fixed in #21 and published as version 4.6.4 to NuGet.
